# 排序节点的组织定义
OrdererOrgs:
  - Name: Orderer # 名称
    Domain: perchain.com # 域名
    Specs: # 节点域名：orderer.perchain.com
      - Hostname: orderer # 主机名

# peer节点的组织定义
PeerOrgs:
  # 中央组织
  - Name: CO # 名称
    Domain: co.perchain.com # 域名
    Template: # 使用模板定义。Count 指的是该组织下组织节点的个数
      Count: 2 # 节点域名：peer0.co.perchain.com 和 peer1.co.perchain.com
    Users: # 组织的用户信息。Count 指该组织中除了 Admin 之外的用户的个数
      Count: 1 # 用户：Admin 和 User1

  # 监管组织
  - Name: SO
    Domain: so.perchain.com
    Template:
      Count: 2 # 节点域名：peer0.so.perchain.com 和 peer1.so.perchain.com
    Users:
      Count: 1 # 用户：Admin 和 User1

  # 审计组织
  - Name: AO
    Domain: ao.perchain.com
    Template:
      Count: 2 # 节点域名：peer0.ao.perchain.com 和 peer1.ao.perchain.com
    Users:
      Count: 1 # 用户：Admin 和 User1